// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device_OsType int32

const (
	Device_IOS     Device_OsType = 0
	Device_ANDROID Device_OsType = 1
)

var Device_OsType_name = map[int32]string{
	0: "IOS",
	1: "ANDROID",
}

var Device_OsType_value = map[string]int32{
	"IOS":     0,
	"ANDROID": 1,
}

func (x Device_OsType) String() string {
	return proto.EnumName(Device_OsType_name, int32(x))
}

func (Device_OsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{0, 0}
}

type Device struct {
	DeviceId             string               `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ReceiveTime          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	Channel              string               `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	AppKey               string               `protobuf:"bytes,4,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	OsType               Device_OsType        `protobuf:"varint,5,opt,name=os_type,json=osType,proto3,enum=proto.Device_OsType" json:"os_type,omitempty"`
	OsVersion            string               `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Language             string               `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Resolution           string               `protobuf:"bytes,8,opt,name=resolution,proto3" json:"resolution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Device) GetReceiveTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReceiveTime
	}
	return nil
}

func (m *Device) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Device) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *Device) GetOsType() Device_OsType {
	if m != nil {
		return m.OsType
	}
	return Device_IOS
}

func (m *Device) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Device) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Device) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.Device_OsType", Device_OsType_name, Device_OsType_value)
	proto.RegisterType((*Device)(nil), "proto.Device")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor_870276a56ac00da5) }

var fileDescriptor_870276a56ac00da5 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0x69, 0xff, 0xdd, 0x6d, 0xa7, 0x45, 0xca, 0x22, 0xb8, 0x54, 0xac, 0xa5, 0xa7,
	0x5c, 0xdc, 0x42, 0x3d, 0x7b, 0x10, 0x72, 0x09, 0x82, 0x81, 0x58, 0xbc, 0x86, 0x6d, 0x32, 0xc6,
	0x60, 0x9a, 0x5d, 0xb2, 0x49, 0x20, 0x1f, 0xcf, 0x6f, 0x26, 0xd9, 0x35, 0xe0, 0x69, 0x78, 0x6f,
	0x66, 0x7e, 0xf3, 0x06, 0x56, 0x19, 0x76, 0x45, 0x8a, 0x42, 0xd7, 0xaa, 0x51, 0x6c, 0x66, 0xcb,
	0xe6, 0x3e, 0x57, 0x2a, 0x2f, 0xf1, 0x60, 0xd5, 0xb9, 0xfd, 0x38, 0x34, 0xc5, 0x05, 0x4d, 0x23,
	0x2f, 0xda, 0xcd, 0xed, 0xbf, 0x27, 0x40, 0x02, 0xbb, 0xc8, 0x6e, 0x61, 0xe1, 0x10, 0x49, 0x91,
	0x71, 0x6f, 0xe7, 0xf9, 0x8b, 0x78, 0xee, 0x8c, 0x30, 0x63, 0x4f, 0xb0, 0xaa, 0x31, 0xc5, 0xa2,
	0xc3, 0x64, 0x40, 0xf0, 0xc9, 0xce, 0xf3, 0x97, 0xc7, 0x8d, 0x70, 0x7c, 0x31, 0xf2, 0xc5, 0x69,
	0xe4, 0xc7, 0xcb, 0xdf, 0xf9, 0xc1, 0x61, 0x1c, 0x68, 0xfa, 0x29, 0xab, 0x0a, 0x4b, 0x3e, 0xb5,
	0xe4, 0x51, 0xb2, 0x1b, 0xa0, 0x52, 0xeb, 0xe4, 0x0b, 0x7b, 0xfe, 0xdf, 0x76, 0x88, 0xd4, 0xfa,
	0x05, 0x7b, 0xf6, 0x00, 0x54, 0x99, 0xa4, 0xe9, 0x35, 0xf2, 0xd9, 0xce, 0xf3, 0xaf, 0x8e, 0xd7,
	0xee, 0x8a, 0x70, 0x71, 0x45, 0x64, 0x4e, 0xbd, 0xc6, 0x98, 0x28, 0x5b, 0xd9, 0x1d, 0x80, 0x32,
	0x49, 0x87, 0xb5, 0x29, 0x54, 0xc5, 0x89, 0x45, 0x2d, 0x94, 0x79, 0x77, 0x06, 0xdb, 0xc0, 0xbc,
	0x94, 0x55, 0xde, 0xca, 0x1c, 0x39, 0x75, 0xbf, 0x8d, 0x9a, 0x6d, 0x01, 0x6a, 0x34, 0xaa, 0x6c,
	0x9b, 0x61, 0x75, 0x6e, 0xbb, 0x7f, 0x9c, 0xfd, 0x16, 0x88, 0x3b, 0xc6, 0x28, 0x4c, 0xc3, 0xe8,
	0x6d, 0xfd, 0x8f, 0x2d, 0x81, 0x3e, 0xbf, 0x06, 0x71, 0x14, 0x06, 0x6b, 0xef, 0x4c, 0x6c, 0xae,
	0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0xa0, 0x18, 0xb6, 0x82, 0x01, 0x00, 0x00,
}
