// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Sdk_device_report.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SdkDeviceReport_OsType int32

const (
	SdkDeviceReport_IOS     SdkDeviceReport_OsType = 0
	SdkDeviceReport_ANDROID SdkDeviceReport_OsType = 1
)

var SdkDeviceReport_OsType_name = map[int32]string{
	0: "IOS",
	1: "ANDROID",
}

var SdkDeviceReport_OsType_value = map[string]int32{
	"IOS":     0,
	"ANDROID": 1,
}

func (x SdkDeviceReport_OsType) String() string {
	return proto.EnumName(SdkDeviceReport_OsType_name, int32(x))
}

func (SdkDeviceReport_OsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60c4357c4343f9bd, []int{0, 0}
}

type SdkDeviceReport struct {
	Imei                 string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Idfa                 string                 `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	ReceiveTime          *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	Channel              string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	AppKey               string                 `protobuf:"bytes,5,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	OsType               SdkDeviceReport_OsType `protobuf:"varint,6,opt,name=os_type,json=osType,proto3,enum=proto.SdkDeviceReport_OsType" json:"os_type,omitempty"`
	OsVersion            string                 `protobuf:"bytes,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Language             string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Resolution           string                 `protobuf:"bytes,9,opt,name=resolution,proto3" json:"resolution,omitempty"`
	SourceIp             string                 `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SdkDeviceReport) Reset()         { *m = SdkDeviceReport{} }
func (m *SdkDeviceReport) String() string { return proto.CompactTextString(m) }
func (*SdkDeviceReport) ProtoMessage()    {}
func (*SdkDeviceReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c4357c4343f9bd, []int{0}
}

func (m *SdkDeviceReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkDeviceReport.Unmarshal(m, b)
}
func (m *SdkDeviceReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkDeviceReport.Marshal(b, m, deterministic)
}
func (m *SdkDeviceReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkDeviceReport.Merge(m, src)
}
func (m *SdkDeviceReport) XXX_Size() int {
	return xxx_messageInfo_SdkDeviceReport.Size(m)
}
func (m *SdkDeviceReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkDeviceReport.DiscardUnknown(m)
}

var xxx_messageInfo_SdkDeviceReport proto.InternalMessageInfo

func (m *SdkDeviceReport) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *SdkDeviceReport) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *SdkDeviceReport) GetReceiveTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReceiveTime
	}
	return nil
}

func (m *SdkDeviceReport) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SdkDeviceReport) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *SdkDeviceReport) GetOsType() SdkDeviceReport_OsType {
	if m != nil {
		return m.OsType
	}
	return SdkDeviceReport_IOS
}

func (m *SdkDeviceReport) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *SdkDeviceReport) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SdkDeviceReport) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func (m *SdkDeviceReport) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.SdkDeviceReport_OsType", SdkDeviceReport_OsType_name, SdkDeviceReport_OsType_value)
	proto.RegisterType((*SdkDeviceReport)(nil), "proto.SdkDeviceReport")
}

func init() { proto.RegisterFile("Sdk_device_report.proto", fileDescriptor_60c4357c4343f9bd) }

var fileDescriptor_60c4357c4343f9bd = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcf, 0x6b, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0xf1, 0x47, 0x62, 0xc6, 0x2f, 0xad, 0xec, 0xc5, 0xc5, 0xa2, 0x15, 0x4f, 0x9e,
	0x22, 0x58, 0xe8, 0xad, 0x87, 0x82, 0x17, 0x29, 0x54, 0x88, 0xd2, 0x6b, 0x58, 0x93, 0x31, 0x5d,
	0x8c, 0xd9, 0x65, 0x37, 0x11, 0xf2, 0xb7, 0xf7, 0x52, 0x9c, 0xd5, 0x52, 0x7a, 0x9a, 0x9d, 0xcf,
	0x9b, 0x79, 0x6f, 0x16, 0x86, 0x36, 0x3b, 0x26, 0x19, 0x9e, 0x65, 0x8a, 0x89, 0x41, 0xad, 0x4c,
	0x15, 0x69, 0xa3, 0x2a, 0xc5, 0xba, 0x54, 0x46, 0x8f, 0xb9, 0x52, 0x79, 0x81, 0x0b, 0xea, 0xf6,
	0xf5, 0x61, 0x51, 0xc9, 0x13, 0xda, 0x4a, 0x9c, 0xb4, 0x9b, 0x9b, 0x7d, 0xb5, 0xe0, 0x7e, 0x9b,
	0x1d, 0x57, 0x64, 0x11, 0x93, 0x03, 0x63, 0xd0, 0x91, 0x27, 0x94, 0xdc, 0x9b, 0x7a, 0xf3, 0x30,
	0xa6, 0x37, 0xb1, 0xec, 0x20, 0x78, 0xeb, 0xca, 0xb2, 0x83, 0x60, 0x2f, 0xf0, 0xdf, 0x60, 0x8a,
	0xf2, 0x8c, 0xc9, 0xc5, 0x96, 0xb7, 0xa7, 0xde, 0xbc, 0xbf, 0x1c, 0x45, 0x2e, 0x33, 0xba, 0x65,
	0x46, 0xbb, 0x5b, 0x66, 0xdc, 0xbf, 0xce, 0x5f, 0x08, 0xe3, 0x10, 0xa4, 0x9f, 0xa2, 0x2c, 0xb1,
	0xe0, 0x1d, 0x72, 0xbd, 0xb5, 0x6c, 0x08, 0x81, 0xd0, 0x3a, 0x39, 0x62, 0xc3, 0xbb, 0xa4, 0xf8,
	0x42, 0xeb, 0x37, 0x6c, 0xd8, 0x33, 0x04, 0xca, 0x26, 0x55, 0xa3, 0x91, 0xfb, 0x53, 0x6f, 0x7e,
	0xb7, 0x1c, 0xbb, 0x94, 0xe8, 0xcf, 0x17, 0xa2, 0x8d, 0xdd, 0x35, 0x1a, 0x63, 0x5f, 0x51, 0x65,
	0x63, 0x00, 0x65, 0x93, 0x33, 0x1a, 0x2b, 0x55, 0xc9, 0x03, 0xf2, 0x0c, 0x95, 0xfd, 0x70, 0x80,
	0x8d, 0xa0, 0x57, 0x88, 0x32, 0xaf, 0x45, 0x8e, 0xbc, 0x47, 0xe2, 0x4f, 0xcf, 0x26, 0x00, 0x06,
	0xad, 0x2a, 0xea, 0xea, 0xb2, 0x1a, 0x92, 0xfa, 0x8b, 0xb0, 0x07, 0x08, 0xad, 0xaa, 0x4d, 0x8a,
	0x89, 0xd4, 0x1c, 0xdc, 0xb2, 0x03, 0x6b, 0x3d, 0x9b, 0x80, 0xef, 0x2e, 0x61, 0x01, 0xb4, 0xd7,
	0x9b, 0xed, 0xe0, 0x1f, 0xeb, 0x43, 0xf0, 0xfa, 0xbe, 0x8a, 0x37, 0xeb, 0xd5, 0xc0, 0xdb, 0xfb,
	0x74, 0xfd, 0xd3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x43, 0x6a, 0x22, 0xc7, 0x01, 0x00,
	0x00,
}
