core:
  dsn: ckcclc:141421@tcp(localhost:3306)/gochannel
api:
  address: :8480 
  internal:
    publicKey: publicKey-example
kafka:
  consumer: 
    bootstrap-server: 
      - localhost:9092
    topic: 
      - gochannel
    group-id: gochannel_group

log:
  # text or json
  format: "text"
  # stdout: output to console, or define log path like "log/access_log"
  apiLog: "stdout"
  apiLevel: "debug"
