database:
  dsn: ckcclc:141421@tcp(localhost:3306)/gochannel?multiStatements=true
  max-open-conns: 5
  max-idle-conns: 2

logger:
  api:
    # text or json
    format: "text"
    # stdout: output to console, or define log path like "log/access_log"
    output: "stdout"
    level: "debug"
  match:
    format: "text"
    output: "stdout"
    level: "debug"

elastic:
  server: http://127.0.0.1:9200/
  device:
    index: gochannel-device
    batch-size: 50
  click:
    index: gochannel-click
    batch-size: 50

api.server:
  address: :8480
  internal.pub-key: MIGJAoGBAJaxeQZ0W3/DJUJQy5qoV52UQ3Urxrv4yL0dhqBuBhPItFYa4zQxKdapvMnbaiHpLkIwPN1E5rlQDAAPwO2oNPrb9n0v8zoX4DyOFS9uXjjUBstEqgjA8MfWz5ChvlcuoEqDFcMYsAbBMTBOdjVw6XBPuely9ZCu6Zfj7LrSuGqZAgMBAAE=

kafka:
  bootstrap-server:
      - localhost:9092
  topic:
      - gochannel
  group-id: gochannel_group

activate:
  # 7 days in milliseconds
  valid-period: 604800000

process:
  # 30 sec in milliseconds
  period: 30000
